language: java
services:
- docker
addons:
  ssh_know_hosts: smithlu7@129.194.69.131
  sonarcloud:
    organization: pinfo-2020
    token:
      secure: Hi49MH8gnqEKSPAG+r+ARp1wAp48AEMFC77d0elqVOFMtJpxdSTTDB4rTyAMHRbyGKjVedRk/MaiJ8E98VTINWKjwi+9pPCH3HOsjvwG/D9G36u3lqEsY6ynwty5gHoBX+ugF90N/zMutL0SIzVqdXVSzrrsfcK9cwSILdF0QQesU+YoOf0BcCWpAjxvaiInd9XLhNX1rAUR9zWOZ38sYSvBVVCZ9KvnKL8hh2cz1sNcdvHg+1mWBi0Z1mAPpS3FZ8wk5zLEgYTFv1Xvt+Xbn1zIX5RnlbQWjpJirdnbnXJuL+NIrfXiXD4WTt3jfd73UXA/wFx3M29C41Jg80J5+sT18GOCIvTiSk3QDhZONGa310EpH7TUXB+s6T7S6eVpaR84jgCizXwymNOAq+i/9L5KG6qc2dRr5iCxO7vklbiHnA6I2nOsrYjmwAMTByegnd8+kH4+GE0eIgPmxrvQft2wWV3EeT4i4UpxoU4jBSQsSjv++BWPWfkzUPykqb2uylnYyY3QHF19E/w/JZw5Lk9ifaom5afBDU6c7B1t7bNADlrfjMW+ny/GAzxrRFd2rUNiILyFr7nTR6D2w8bIAuEaO8KaZSIa9WTuJOru76L8xQmUi9mvM6ur7USm9bKHn3XcL03qNLI/teDFt3u1f7Wx4+Mx3+ynJE6xLUjXXfU=

jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
    - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: Build
    script:
    - mvn install -Ppackage-docker-image
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/api-gateway pinfo4/api-gateway:latest
    - docker tag unige/regulatory-service pinfo4/regulatory-service:latest
    - docker tag unige/valuation-service pinfo4/valuation-service:latest
    - docker tag unige/instrument-service pinfo4/instrument-service:latest
    - docker tag unige/counterparty-service pinfo4/counterparty-service:latest
    - docker push pinfo4/api-gateway:latest
    - docker push pinfo4/regulatory-service:latest
    - docker push pinfo4/valuation-service:latest
    - docker push pinfo4/instrument-service:latest
    - docker push pinfo4/counterparty-service:latest
    - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dcc92ae7dc64eccb859dcb446883d405a94733bd -Dsonar.projectName=Kernel_pinfo4
  - stage: Build
    script:
    - cd web-ui
    - pwd
    - npm -v
    - npm install
    - npm update
    - npm run-script build --prod
    - docker build -t unige/web-ui .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/web-ui pinfo4/web-ui:latest
    - docker push pinfo4/web-ui:latest

before_deploy: # Decrypts the ssh-key for the VM connection
  - openssl aes-256-cbc -K $encrypted_ba497ca00145_key -iv $encrypted_ba497ca00145_iv -in pinfo4_deploy_rsa.enc -out /tmp/pinfo4_deploy_rsa -d
  - eval "$(ssh-agent -s)" # 'eval' to load the ssh-agent variables into the current environment upon starting of the ssh-agent, which we will use for logging in to the VM
  - chmod 600 /tmp/pinfo4_deploy_rsa
  - ssh-add /tmp/pinfo4_deploy_rsa

deploy:
  provider: script
  skip_cleanup: true # Avoid Travis resetting the git directory state
  script: ssh smithlu7@129.194.69.131 'bash ' < deploy_script.sh # TODO: Write the deploy script
  on:
    branch: master # Only deploy if the master branch has been updated
