language: java
env:
  - NODE_VERSION="12.13.1"

services:
  - docker

addons:
  sonarcloud:
    organization: "pinfo-2020"
    token:
      secure: "HgPKI5uK0oHCnV36ee2dvOoql3OhTI01pnypnkFNfzzXlggfCqHHIKWIHYUZkVv8K0p7VgcNsycSiOJK/+q3yMuNVsb33+7tv65idsGjI+ctmnUIlCfhoxDkEE7BNY0Fm2wf0TTMvcKeupLMbw+tCP7JcqZ8JWphhfxNVlPYG+A2EubYd7jYMR17ZGZqbL1u/Rjvsfy057faNEmEvoCkIed7qZLZBsIUwQNIwG9tnVzKbecTgpiyUSHXRyMpGNpm7MbukY2COYqqYAXTdHFBv2yAXJEGMDkYw4J59ILSBN8YVaGTEydMpqbsV6yGIkj16BbvHogP9O27aDwFyIlwirXGQVYE0iAqLc7A2S0MTJ8RZcK/ubLYuxHjU1nsDd1RvvHGyAsL52cNMwOSD21WQ9GMJmhSd7ndJfDGznsGSS8ORnsW2MovW7YRL8jdDZRW0Mz6yxn2w2ke32Lwah7yiAIlpz6mKf85C2tPuMkMMwsF4uwbPtcS4hhfd4FGLp9OHmEBEPqKD5rGPuErn4+g8wNJw5rMWskpEHtdmvIunJjZZ/qgyTBCSnCdpsP/DF3mU69mg/8R1aiqUsq0HRjgQDf450VG8zdedK8Tqjj71ygCLVtJR4Q0ObKF+qjW7IjcfQxDCKw6AIJn9+mdD823ifoYDMFnqqZqBkIwrNlAleU="

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules

script:
  - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=439228460b4bd7f556f1da62fd172f4a619e2b63
# jobs:
#   include:
#   - stage: Prepare
#     script:
#     - nvm install $NODE_VERSION
#     - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#   - stage: Build
#     script:
#     - mvn install -Ppackage-docker-image
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker tag unige/api-gateway pinfo4/api-gateway:latest
#     - docker tag unige/regulatory-service pinfo4/regulatory-service:latest
#     - docker tag unige/valuation-service pinfo4/valuation-service:latest
#     - docker tag unige/instrument-service pinfo4/instrument-service:latest
#     - docker tag unige/counterparty-service pinfo4/counterparty-service:latest
#     - docker push pinfo4/api-gateway:latest
#     - docker push pinfo4/regulatory-service:latest
#     - docker push pinfo4/valuation-service:latest
#     - docker push pinfo4/instrument-service:latest
#     - docker push pinfo4/counterparty-service:latest
#     - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020
#       -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=439228460b4bd7f556f1da62fd172f4a619e2b63
#   - stage: Build
#     script:
#     - cd web-ui
#     - pwd
#     - npm -v
#     - npm install
#     - npm update
#     - npm run-script build --prod
#     - docker build -t unige/web-ui .
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker tag unige/web-ui pinfo4/web-ui:latest
    - docker push pinfo4/web-ui:latest
