language: java
env:
  - NODE_VERSION="12.13.1"

services:
  - docker

addons:
  sonarcloud:
    organization: "pinfo-2020"
    token:
      secure: "ekMcNm2FzLJbEsmUP4W0GR2bU6EBpBcdfVELS2eXzM11aybMZKjD7D5+4r8utx/bbcfFWkaCFJXts/3+C/sFJplrGw7AdYsynS0qRHGLtfSlc9bxof3hhLW7vWmqd1bCMx1mJ8MKsMy1Gt4nhMc1Dw/PTg3R1GDjMuKgHRciMsYGV2HYhu4pmxp0a0PhGym3NKTRpWftYRVqH6mdoL4yoQEPOsdGt3CK2hXkQ7Ded9h6dFHNWqd+67rtdXw4YhSF4AJrN6LUWSHPoHfu92HKaH5HOEDwFMH1EjX3PBn2bT+2MElFS8Y5GaTqnIE7V3QLmSthUhjtxVpwCZVfTx1bgWCiw7LcqBvhr4eF1wR/Ulyd0/+ZV6I/hMK+7t0Tll0L9pwrQDSNzATrvT6OclSxuWvgKXVUjJ7oJMxOqi60PQkhGIzCQHvIhrIgEK5b1kpmVWnqcPRb0cXhhFV7rJIxQflRTNLLNsMusg88rI8g4hODIhJ12EJhIFOdEXqVASiyG8nW4g37yeofBvjzDgeFArCwdTnKHpczMZe4wk6SjgCs5lpcBzf3qJp9G4a02UuZDv6HKSyMzMrYpOuPJF1lcvfywjNvn+fNRjVaJDCS9eEK1MKvOlxF7gdGlXtMiVpLP5famn9TbytIePawV4TZMylIS4n+zZ40RYLv3uAu+fo="

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - node_modules

jobs:
  include:
  - stage: Prepare
    script:
    - nvm install $NODE_VERSION
    - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: Build
    script:
    - mvn install -Ppackage-docker-image
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/api-gateway pinfo4/api-gateway:latest
    - docker tag unige/regulatory-service pinfo4/regulatory-service:latest
    - docker tag unige/valuation-service pinfo4/valuation-service:latest
    - docker tag unige/instrument-service pinfo4/instrument-service:latest
    - docker tag unige/counterparty-service pinfo4/counterparty-service:latest
    - docker push pinfo4/api-gateway:latest
    - docker push pinfo4/regulatory-service:latest
    - docker push pinfo4/valuation-service:latest
    - docker push pinfo4/instrument-service:latest
    - docker push pinfo4/counterparty-service:latest
    - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020
      -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3219041e351b0379aaa64344d9a1b8e53b615999
  - stage: Build
    script:
    - cd web-ui
    - pwd
    - npm -v
    - npm install
    - npm update
    - npm run-script build --prod
    - docker build -t unige/web-ui .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag unige/web-ui pinfo4/web-ui:latest
    - docker push pinfo4/web-ui:latest
