language: java
# env:
#   - NODE_VERSION="12.13.1"

services:
  - docker

addons:
  sonarcloud:
    organization: "pinfo-2020"
    # token:
      # secure: "usH7crPRoWq2qvpmUxqA6KGdQVWN4HwHR3MjMO9mhB7GQw4prCvDlSgRGDIbDnEVoxechdjhVKH+r4QrhZWBspOXeQOLQKYOUstmaD2lSQMO9oQxBgP+rYJCOWPDVaKsqY2U1PzhEXF3T3CL0oYHPEwK0lmA70WYrPlaJJ+vIJYNDlyoALS9MeactkwJPBIW10ll2rPp+OtqWqSRHF3qxMD/W6HM1qbkDFfjLRij+dNlrC4rR7YOGKJDf82267D20oQwCxbMIPnTEJSA/ek5nRCWgkG4qpP2yKQqyuMhl8dj0CSPdEjSxnjd7sQAdDu2mjWtYMZ5S+12IcFl5CUQyhY4fmOBVg58bvl9avVoLFr3l0mRdvYLnpzK5vjcBw6pHzjUTT4BQFXOMD6wJB8SI50vx/hrVI97z3vvwMh8N2aplibQuX/X4+w+Pujs473rSpk0HfuBqYns+Qs4v8bs6lRSeRtYa2oSwkHD5Rl0ybTT2thAf85Ilb4rZF3T5T+zWFpYl2wuRgFpgJy+kQhQg0hk756vwAxRKS0QwycWryGs52SF73TLC0M2WNPSqdAVK3Qameqkdxnnhh3M4gW9CL0/kfd+OkWQOKS/IuCmlvWbFXnsKGBRDDIQ/IZaRsDcE86OvAIL4ieq0c9eHTeQuRwIVSa7b0FC2Yudui15zns="

# cache:
#   directories:
#     - ".autoconf"
#     - "$HOME/.m2"
#     - node_modules

script:
  - mvn test
  - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dcc92ae7dc64eccb859dcb446883d405a94733bd

  # - mvn -X clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=pinfo-2020 -Dsonar.projectKey=PInfo-2020_PInfo-4
  # - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1ad19aa39f53aa63ef6946817fe487c35257029a

# jobs:
#   include:
#   - stage: Prepare
#     script:
#     - nvm install $NODE_VERSION
#     - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#   - stage: Build
#     script:
#     - mvn install -Ppackage-docker-image
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker tag unige/api-gateway pinfo4/api-gateway:latest
#     - docker tag unige/regulatory-service pinfo4/regulatory-service:latest
#     - docker tag unige/valuation-service pinfo4/valuation-service:latest
#     - docker tag unige/instrument-service pinfo4/instrument-service:latest
#     - docker tag unige/counterparty-service pinfo4/counterparty-service:latest
#     - docker push pinfo4/api-gateway:latest
#     - docker push pinfo4/regulatory-service:latest
#     - docker push pinfo4/valuation-service:latest
#     - docker push pinfo4/instrument-service:latest
#     - docker push pinfo4/counterparty-service:latest
#     - mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-4 -Dsonar.organization=pinfo-2020
#       -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=439228460b4bd7f556f1da62fd172f4a619e2b63
#   - stage: Build
#     script:
#     - cd web-ui
#     - pwd
#     - npm -v
#     - npm install
#     - npm update
#     - npm run-script build --prod
#     - docker build -t unige/web-ui .
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker tag unige/web-ui pinfo4/web-ui:latest
    # - docker push pinfo4/web-ui:latest
