apiVersion: v1
kind: PersistentVolume
metadata:
  name: loginpage-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "config/login_page/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loginpage-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Mi
