version: "3.5"

services:

  ingredient-database:
    image: postgres:10
    container_name: ingredient-database
    hostname: ingredient-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: ingredient
      POSTGRES_PASSWORD: ingredient
      POSTGRES_DB: ingredient
    volumes:
      - pgdata-frige:/var/lib/postgresql/data
      - ../deploy/sql/ingredient_data.sql
    restart: on-failure
    stdin_open: true
    tty: true
